import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { verifyWayForPaySignature, buildWayForPayAck, type WayForPayCallback } from "@/lib/wayforpay";
import { sendTelegramDownloadMessage } from "@/lib/sendpulse";
import { createHash, randomBytes } from "node:crypto";

// This is the piece that was entirely missing: server-to-server payment
// confirmation. Until now, "payment succeeded" only existed as a browser
// redirect the buyer's own device controlled — anyone could open the
// thank-you page without paying. This endpoint is the single source of
// truth WayForPay itself calls, which nothing on the client can forge
// (protected by the HMAC signature check below).
export async function POST(req: NextRequest) {
  const payload = (await req.json()) as WayForPayCallback;
  const secretKey = process.env.WAYFORPAY_SECRET_KEY;
  if (!secretKey) {
    console.error("WAYFORPAY_SECRET_KEY not configured");
    return NextResponse.json({ error: "server not configured" }, { status: 500 });
  }

  if (!verifyWayForPaySignature(payload, secretKey)) {
    console.warn("WayForPay webhook: signature mismatch", payload.orderReference);
    return NextResponse.json({ error: "invalid signature" }, { status: 400 });
  }

  // orderReference is generated by /api/checkout/start as `${productSlug}__${telegramContactId}__${randomId}`
  // so this handler can recover who to notify without a separate lookup table.
  const [productSlug, telegramContactId] = payload.orderReference.split("__");

  if (payload.transactionStatus === "Approved") {
    const product = await prisma.product.findUnique({ where: { slug: productSlug } });
    if (!product) {
      console.error("WayForPay webhook: unknown product slug", productSlug);
      return NextResponse.json(buildWayForPayAck(payload.orderReference, payload.merchantAccount, secretKey));
    }

    const user = await prisma.user.upsert({
      where: { telegramId: telegramContactId },
      create: { telegramId: telegramContactId },
      update: {},
    });

    // Unique on (provider, providerRef) — WayForPay retries callbacks until
    // acked, so a second delivery of the same orderReference must be a
    // no-op, not a duplicate purchase/entitlement/message.
    const purchase = await prisma.purchase.upsert({
      where: { provider_providerRef: { provider: "wayforpay", providerRef: payload.orderReference } },
      create: {
        userId: user.id,
        productId: product.id,
        provider: "wayforpay",
        providerRef: payload.orderReference,
        amountCents: Math.round(payload.amount * 100),
        currency: payload.currency,
        status: "paid",
      },
      update: { status: "paid" },
    });

    const entitlement = await prisma.entitlement.upsert({
      where: { userId_productId: { userId: user.id, productId: product.id } },
      create: { userId: user.id, productId: product.id, purchaseId: purchase.id, status: "active" },
      update: { status: "active", purchaseId: purchase.id, revokedAt: null },
    });

    // Only send the Telegram message (and mint a token) on a genuinely new
    // purchase — a webhook retry for an already-fulfilled order must not
    // re-send the message or reset the download-count clock.
    const alreadyFulfilled = purchase.status === "paid" && (await prisma.downloadToken.count({ where: { userId: user.id } })) > 0;
    if (!alreadyFulfilled) {
      const libraryItem = await prisma.libraryItem.findFirst({ where: { productId: product.id } });
      if (libraryItem) {
        const rawToken = randomBytes(32).toString("hex");
        const tokenHash = createHash("sha256").update(rawToken).digest("hex");
        await prisma.downloadToken.create({
          data: {
            userId: user.id,
            contentFileId: libraryItem.contentFileId,
            tokenHash,
            expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000), // 72h MVP default
            maxDownloads: 5, // MVP default
          },
        });
        const downloadUrl = `${process.env.NEXT_PUBLIC_SITE_URL}/api/content/download/${rawToken}`;
        try {
          await sendTelegramDownloadMessage(telegramContactId, downloadUrl, libraryItem.title);
        } catch (err) {
          // Purchase/entitlement are already durably recorded — a failed
          // notification must not roll those back. Log for manual retry
          // (see [[docs/... admin]] once the admin panel exists).
          console.error("Failed to notify buyer via SendPulse", err);
        }
      }
    }
    void entitlement; // recorded; not otherwise used in this handler
  }

  return NextResponse.json(buildWayForPayAck(payload.orderReference, payload.merchantAccount, secretKey));
}
